# Generated by Django 4.2.24 on 2025-11-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='公開日'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
